on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          chache: 'npm'
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v1
        with:
          name: build
          path: .\dist
      - uses: actions/deploy-pages@v4